In [299]:
import pandas as pd

In [300]:
al_stats = pd.read_csv("alcyyoungstats.csv")

In [301]:
nl_stats = pd.read_csv("nlcyyoungstats.csv")

In [302]:
#Converts Vote Share to a decimal, as for the data was stored as percentages
nl_stats['Share'] = nl_stats['Share'].str.rstrip('%').astype('float') / 100.0
al_stats['Share'] = al_stats['Share'].str.rstrip('%').astype('float') / 100.0

In [303]:
al_stats

,Unnamed: 0,Name,Age,Tm,Lg,W_x,L_x,W-L%_x,ERA,G,...,Road,ExInn,1Run,vRHP,vLHP,â‰¥.500,<.500,last10,last20,last30
0,0,A.J. Achter,25,MIN,AL,1,0,1.000,3.27,7,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
1,1,Aaron Thompson,27,MIN,AL,0,0,NaN,2.45,7,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
2,2,Anthony Swarzak,28,MIN,AL,3,2,0.600,4.60,50,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
3,3,Brian Duensing,31,MIN,AL,3,3,0.500,3.31,62,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
4,4,Caleb Thielbar,27,MIN,AL,2,1,0.667,3.40,54,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249,7249,Luke Gregerson,30,OAK,AL,5,5,0.500,2.12,72,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18
7250,7250,Ryan Cook,27,OAK,AL,1,3,0.250,3.42,54,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18
7251,7251,Scott Kazmir,30,OAK,AL,15,9,0.625,3.55,32,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18
7252,7252,Sean Doolittle,27,OAK,AL,2,4,0.333,2.73,61,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18
7253,7253,Sonny Gray,24,OAK,AL,14,10,0.583,3.08,33,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18

In [304]:
#Removes unnecessary column
del al_stats["Unnamed: 0"]
del nl_stats["Unnamed: 0"]

In [305]:
pd.isnull(al_stats).sum().head(50)

Name            0
Age             0
Tm              0
Lg              0
W_x             0
L_x             0
W-L%_x       1534
ERA             1
G               0
GS              0
GF              0
CG              0
SHO             0
SV              0
IP              0
H               0
R_x             0
ER              0
HR              0
BB              0
IBB             0
SO              0
HBP             0
BK              0
WP              0
BF              0
ERA+          277
FIP             6
WHIP            6
H9              6
HR9             6
BB9             6
SO9             6
SO/W          317
Year            0
Vote Pts        0
1st Place       0
Share           0
Team            0
Rk              0
W_y             0
L_y             0
W-L%_y          0
Strk            0
R_y             0
RA              0
Rdiff           0
SOS             0
SRS             0
pythWL          0
dtype: int64

In [306]:
#Fills NAN values with 0, for players who played before SABER and StatCast era. Also fixes players who don't have W-L such as RPs
al_stats = al_stats.fillna(0)
nl_stats = nl_stats.fillna(0)

In [307]:
al_stats.columns

Index(['Name', 'Age', 'Tm', 'Lg', 'W_x', 'L_x', 'W-L%_x', 'ERA', 'G', 'GS',
       'GF', 'CG', 'SHO', 'SV', 'IP', 'H', 'R_x', 'ER', 'HR', 'BB', 'IBB',
       'SO', 'HBP', 'BK', 'WP', 'BF', 'ERA+', 'FIP', 'WHIP', 'H9', 'HR9',
       'BB9', 'SO9', 'SO/W', 'Year', 'Vote Pts', '1st Place', 'Share', 'Team',
       'Rk', 'W_y', 'L_y', 'W-L%_y', 'Strk', 'R_y', 'RA', 'Rdiff', 'SOS',
       'SRS', 'pythWL', 'Luck', 'vEast', 'vCent', 'vWest', 'Inter', 'Home',
       'Road', 'ExInn', '1Run', 'vRHP', 'vLHP', 'â‰¥.500', '<.500', 'last10',
       'last20', 'last30'],
      dtype='object')

In [308]:
#Manually removing string columns and columns we are trying to predict
predictors = ['Age', 'W_x', 'L_x', 'W-L%_x', 'ERA', 'G', 'GS',
       'GF', 'CG', 'SHO', 'SV', 'IP', 'H', 'R_x', 'ER', 'HR', 'BB', 'IBB',
       'SO', 'HBP', 'BK', 'WP', 'BF', 'ERA+', 'FIP', 'WHIP', 'H9', 'HR9',
       'BB9', 'SO9', 'SO/W', 'Year', 'W_y', 'L_y', 'W-L%_y', 'R_y', 'RA', 'Rdiff', 'SOS',
       'SRS', 'Luck']

In [309]:
#Sets up training data aka the years before 2023
al_train = al_stats[al_stats["Year"] < 2023]
nl_train = nl_stats[nl_stats["Year"] < 2023]

In [310]:
#Year we are trying to predict
al_test = al_stats[al_stats["Year"] == 2023]
nl_test = nl_stats[nl_stats["Year"] == 2023]

In [311]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [312]:
al_train.sort_values(by="ERA").tail(50)

,Name,Age,Tm,Lg,W_x,L_x,W-L%_x,ERA,G,GS,...,Road,ExInn,1Run,vRHP,vLHP,â‰¥.500,<.500,last10,last20,last30
4560,Robel GarcÃ­a,28,HOU,AL,0,0,0.0,36.00,1,0,...,51-30,1-8,20-21,62-51,28-21,42-43,48-29,6-4,10-10,16-14
5303,Richard UreÃ±a,23,TOR,AL,0,0,0.0,36.00,1,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
5285,Travis Demeritte,25,DET,AL,0,0,0.0,36.00,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
4908,Dylan Moore,26,SEA,AL,0,0,0.0,36.00,1,0,...,43-38,6-14,25-26,66-55,22-19,38-48,50-26,4-6,9-11,13-17
3780,Jace Peterson,28,BAL,AL,0,0,0.0,36.00,1,0,...,52-29,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12
2512,Colten Brewer,28,BOS,AL,0,0,0.0,36.00,1,0,...,39-42,4-6,18-25,54-66,24-18,51-55,27-29,3-7,6-14,9-21
1454,Taylor Cole,27,TOR,AL,0,0,0.0,36.00,1,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
4784,Shohei Ohtani,25,LAA,AL,0,1,0.0,37.80,2,2,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
600,FÃ©lix PeÃ±a,31,LAA,AL,0,0,0.0,37.80,2,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
4774,JosÃ© Suarez,22,LAA,AL,0,2,0.0,38.57,2,2,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
824,Drew Anderson,26,CHW,AL,0,1,0.0,40.50,1,0,...,30-51,5-11,19-30,47-77,14-24,26-59,35-42,3-7,6-14,9-21
1334,Sean Nolin,23,TOR,AL,0,1,0.0,40.50,1,1,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
1304,Sam Dyson,24,TOR,AL,0,0,0.0,40.50,2,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
6860,Juan Nicasio,33,TEX,AL,0,0,0.0,40.50,2,0,...,40-41,2-8,14-22,62-56,28-16,42-45,48-27,6-4,12-8,15-15
1648,Chris Rowley,27,TOR,AL,0,1,0.0,40.50,2,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
3377,Anthony Banda,28,NYY,AL,0,0,0.0,40.50,2,0,...,40-41,6-9,17-23,67-67,15-13,47-46,35-34,6-4,12-8,18-12
1185,Joe Beimel,27,MIN,AL,0,0,0.0,43.20,3,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
649,Aaron Brooks,24,KCR,AL,0,1,0.0,43.88,2,1,...,23-58,3-4,21-20,42-79,14-27,25-60,31-46,6-4,12-8,15-15
1842,Willians Astudillo,26,MIN,AL,0,0,0.0,45.00,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
6230,Jason Anderson,25,CLE,AL,0,0,0.0,45.00,1,0,...,34-47,11-9,27-31,52-51,24-35,41-45,35-41,4-6,8-12,14-16
1823,Chris Gimenez,35,MIN,AL,0,0,0.0,45.00,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
4220,Jacob Turner,27,DET,AL,0,1,0.0,45.00,1,1,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
2242,Adam Johnson,23,MIN,AL,0,1,0.0,47.25,2,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
6527,Brian Tallet,33,TOR,AL,0,1,0.0,54.00,1,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
5979,Drew Butera,34,KCR,AL,0,0,0.0,54.00,1,0,...,23-58,3-4,21-20,42-79,14-27,25-60,31-46,6-4,12-8,15-15
716,Jeremy Bleich,31,OAK,AL,0,0,0.0,54.00,2,0,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18
922,Kyle Nelson,23,CLE,AL,0,0,0.0,54.00,1,0,...,34-47,11-9,27-31,52-51,24-35,41-45,35-41,4-6,8-12,14-16
3803,Cody Carroll,27,BAL,AL,0,0,0.0,54.00,3,0,...,52-29,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12
2729,Mike Zagurski,30,NYY,AL,0,0,0.0,54.00,1,0,...,40-41,6-9,17-23,67-67,15-13,47-46,35-34,6-4,12-8,18-12
2543,Dave Maurer,29,TOR,AL,0,0,0.0,54.00,3,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
5271,David McKay,25,DET,AL,0,0,0.0,54.00,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
1891,Tim Redding,27,NYY,AL,0,1,0.0,54.00,1,1,...,40-41,6-9,17-23,67-67,15-13,47-46,35-34,6-4,12-8,18-12
7068,Josh Wall,27,LAA,AL,0,0,0.0,54.00,2,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
1486,Brian Moran,33,LAA,AL,0,0,0.0,54.00,1,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
1437,Glenn Sparkman,25,TOR,AL,0,0,0.0,63.00,2,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
3458,Radhames Liz,25,BAL,AL,0,0,0.0,67.50,2,0,...,52-29,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12
4428,Jay Sborz,25,DET,AL,0,0,0.0,67.50,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
7112,Edwar Colina,23,MIN,AL,0,0,0.0,81.00,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
655,Donnie Joseph,26,KCR,AL,0,0,0.0,81.00,1,0,...,23-58,3-4,21-20,42-79,14-27,25-60,31-46,6-4,12-8,15-15
2294,Carlos GÃ³mez,32,TBR,AL,0,0,0.0,81.00,1,0,...,46-35,7-5,22-25,75-52,24-11,48-44,51-19,6-4,13-7,19-11
5872,JosÃ© Paniagua,29,CHW,AL,0,0,0.0,108.00,1,0,...,30-51,5-11,19-30,47-77,14-24,26-59,35-42,3-7,6-14,9-21
4209,William Cuevas,26,DET,AL,0,0,0.0,108.00,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
5787,David Carpenter,25,LAA,AL,0,0,0.0,108.00,1,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
3111,Taylor Hearn,24,TEX,AL,0,1,0.0,108.00,1,1,...,40-41,2-8,14-22,62-56,28-16,42-45,48-27,6-4,12-8,15-15
3515,Jeff Ridgway,26,TBD,AL,0,0,0.0,189.00,3,0,...,46-35,7-5,22-25,75-52,24-11,48-44,51-19,6-4,13-7,19-11
2214,Nate Jones,28,CHW,AL,0,0,0.0,inf,2,0,...,30-51,5-11,19-30,47-77,14-24,26-59,35-42,3-7,6-14,9-21
854,Jonathan Stiever,24,CHW,AL,0,0,0.0,inf,1,0,...,30-51,5-11,19-30,47-77,14-24,26-59,35-42,3-7,6-14,9-21
1978,Matt Perisho,30,BOS,AL,0,0,0.0,inf,1,0,...,39-42,4-6,18-25,54-66,24-18,51-55,27-29,3-7,6-14,9-21
5024,Andrew Vasquez,25,MIN,AL,0,0,0.0,inf,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
3277,Lino Urdaneta,24,DET,AL,0,0,0.0,inf,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11

In [313]:
nl_train.sort_values(by="ERA").tail(50)

,Name,Age,Tm,Lg,W_x,L_x,W-L%_x,ERA,G,GS,...,Road,ExInn,1Run,vRHP,vLHP,â‰¥.500,<.500,last10,last20,last30
6803,Joe Paterson,26,ARI,NL,0,0,0.0,37.13,6,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
1826,Roman Quinn,25,PHI,NL,0,0,0.0,37.80,1,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
1223,Josh VanMeter,27,PIT,NL,0,0,0.0,39.00,3,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
5562,Blaine Boyer,24,ATL,NL,0,0,0.0,40.50,2,0,...,52-29,8-3,23-18,81-49,23-9,55-33,49-25,7-3,11-9,17-13
543,Curtis Partch,29,PIT,NL,0,0,0.0,40.50,2,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
3455,Brendon Little,25,CHC,NL,0,1,0.0,40.50,1,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
5795,Antonio Osuna,32,WSN,NL,0,0,0.0,42.43,4,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
5204,Dave Davidson,25,FLA,NL,0,0,0.0,45.00,1,0,...,38-43,7-3,33-14,64-59,20-19,38-50,46-28,5-5,11-9,18-12
4135,Max Schrock,27,CIN,NL,0,0,0.0,45.00,1,0,...,44-37,10-5,34-29,59-55,23-25,41-47,41-33,3-7,9-11,14-16
1612,Todd Zeile,38,NYM,NL,0,0,0.0,45.00,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
1992,Patrick Schuster,25,PHI,NL,0,1,0.0,45.00,6,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
3453,Andrelton Simmons,32,CHC,NL,0,0,0.0,45.00,1,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
6135,Jordan Weems,28,ARI,NL,0,1,0.0,47.25,2,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
1429,Paul Janish,26,CIN,NL,0,0,0.0,49.50,2,0,...,44-37,10-5,34-29,59-55,23-25,41-47,41-33,3-7,9-11,14-16
4651,Matt Grace,31,ARI,NL,0,1,0.0,54.00,3,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
3851,Vin Mazzaro,29,SFG,NL,1,0,1.0,54.00,2,0,...,34-47,11-5,25-19,51-63,28-20,46-55,33-28,3-7,7-13,10-20
835,John Axford,38,MIL,NL,0,0,0.0,54.00,1,0,...,43-38,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12
1090,Dan Serafini,33,COL,NL,0,0,0.0,54.00,3,0,...,22-59,6-4,23-24,37-74,22-29,31-72,28-31,3-7,8-12,10-20
5352,Jared FernÃ¡ndez,32,HOU,NL,0,0,0.0,54.00,2,1,...,51-30,1-8,20-21,62-51,28-21,42-43,48-29,6-4,10-10,16-14
2577,Mike Bynum,26,SDP,NL,0,1,0.0,54.00,2,0,...,38-43,2-12,9-23,54-61,28-19,40-51,42-29,8-2,15-5,20-10
904,James Bourque,25,WSN,NL,0,0,0.0,54.00,1,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
7737,Yunesky Maya,31,WSN,NL,0,1,0.0,54.00,1,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
2350,Deolis Guerra,30,MIL,NL,0,0,0.0,54.00,1,0,...,43-38,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12
5719,Nate Robertson,32,PHI,NL,0,0,0.0,54.00,2,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
2439,Sandy Rosario,24,FLA,NL,0,0,0.0,54.00,2,0,...,38-43,7-3,33-14,64-59,20-19,38-50,46-28,5-5,11-9,18-12
746,JosÃ© Reyes,35,NYM,NL,0,0,0.0,54.00,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
7335,Jason Pearson,27,STL,NL,0,0,0.0,63.00,2,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
2337,Mike Zagurski,35,MIL,NL,0,1,0.0,63.00,2,0,...,43-38,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12
4812,Trevor Bell,27,CIN,NL,0,0,0.0,67.50,2,0,...,44-37,10-5,34-29,59-55,23-25,41-47,41-33,3-7,9-11,14-16
3428,Brailyn MÃ¡rquez,21,CHC,NL,0,0,0.0,67.50,1,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
3533,Akeel Morris,22,NYM,NL,0,0,0.0,67.50,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
5770,Casper Wells,28,PHI,NL,0,1,0.0,67.50,1,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
3337,Roel RamÃ­rez,25,STL,NL,0,0,0.0,81.00,1,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
2819,Enrique HernÃ¡ndez,26,LAD,NL,0,1,0.0,81.00,1,0,...,47-34,6-6,16-15,74-39,26-23,52-36,48-26,6-4,13-7,17-13
3366,Roel RamÃ­rez,26,STL,NL,0,0,0.0,81.00,1,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
5990,Ã‰dgar GonzÃ¡lez,22,ARI,NL,0,0,0.0,108.00,1,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
6758,Garrett Olson,28,NYM,NL,0,0,0.0,108.00,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
220,Jeremy Guthrie,38,WSN,NL,0,1,0.0,135.00,1,1,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
3901,Alex Hinshaw,29,CHC,NL,0,0,0.0,135.00,2,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
1714,Chad Fox,38,CHC,NL,0,0,0.0,135.00,2,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
895,Austen Williams,26,WSN,NL,0,0,0.0,162.00,2,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
4230,Zack Weiss,26,CIN,NL,0,0,0.0,inf,1,0,...,44-37,10-5,34-29,59-55,23-25,41-47,41-33,3-7,9-11,14-16
2546,Dennis Tankersley,24,SDP,NL,0,1,0.0,inf,1,1,...,38-43,2-12,9-23,54-61,28-19,40-51,42-29,8-2,15-5,20-10
1893,Stephen Tarpley,28,NYM,NL,0,0,0.0,inf,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
3216,Nick Greenwood,27,STL,NL,0,1,0.0,inf,1,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
75,Daniel McCutchen,29,PIT,NL,0,1,0.0,inf,1,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
902,Gerardo Parra,32,WSN,NL,0,0,0.0,inf,1,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
5085,Matt Koch,26,ARI,NL,0,0,0.0,inf,1,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
311,Rex Brothers,30,ATL,NL,0,0,0.0,inf,1,0,...,52-29,8-3,23-18,81-49,23-9,55-33,49-25,7-3,11-9,17-13
3346,Bernardo Flores Jr.,25,STL,NL,0,0,0.0,inf,1,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15

In [314]:
#Removes players with infinite ERAs, definitely hinders accuracy but for now I cannot find a work around
al_train = al_train.replace([np.inf, -np.inf], np.nan)
al_train = al_train.dropna(subset=['ERA'])
nl_train = nl_train.replace([np.inf, -np.inf], np.nan)
nl_train = nl_train.dropna(subset=['ERA'])

In [315]:
al_train.sort_values(by="ERA").tail(50)

,Name,Age,Tm,Lg,W_x,L_x,W-L%_x,ERA,G,GS,...,Road,ExInn,1Run,vRHP,vLHP,â‰¥.500,<.500,last10,last20,last30
676,Chad Smith,25,OAK,AL,0,0,0.0,33.75,2,0,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18
4560,Robel GarcÃ­a,28,HOU,AL,0,0,0.0,36.00,1,0,...,51-30,1-8,20-21,62-51,28-21,42-43,48-29,6-4,10-10,16-14
4453,Mark Worrell,28,BAL,AL,0,0,0.0,36.00,4,0,...,52-29,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12
437,Brett Nicholas,28,TEX,AL,0,0,0.0,36.00,1,0,...,40-41,2-8,14-22,62-56,28-16,42-45,48-27,6-4,12-8,15-15
5026,Chase De Jong,25,MIN,AL,0,0,0.0,36.00,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
4908,Dylan Moore,26,SEA,AL,0,0,0.0,36.00,1,0,...,43-38,6-14,25-26,66-55,22-19,38-48,50-26,4-6,9-11,13-17
5285,Travis Demeritte,25,DET,AL,0,0,0.0,36.00,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
5303,Richard UreÃ±a,23,TOR,AL,0,0,0.0,36.00,1,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
3780,Jace Peterson,28,BAL,AL,0,0,0.0,36.00,1,0,...,52-29,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12
2512,Colten Brewer,28,BOS,AL,0,0,0.0,36.00,1,0,...,39-42,4-6,18-25,54-66,24-18,51-55,27-29,3-7,6-14,9-21
1454,Taylor Cole,27,TOR,AL,0,0,0.0,36.00,1,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
6700,Luis Mendoza,25,TEX,AL,0,0,0.0,36.00,1,0,...,40-41,2-8,14-22,62-56,28-16,42-45,48-27,6-4,12-8,15-15
4784,Shohei Ohtani,25,LAA,AL,0,1,0.0,37.80,2,2,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
600,FÃ©lix PeÃ±a,31,LAA,AL,0,0,0.0,37.80,2,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
4774,JosÃ© Suarez,22,LAA,AL,0,2,0.0,38.57,2,2,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
824,Drew Anderson,26,CHW,AL,0,1,0.0,40.50,1,0,...,30-51,5-11,19-30,47-77,14-24,26-59,35-42,3-7,6-14,9-21
1334,Sean Nolin,23,TOR,AL,0,1,0.0,40.50,1,1,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
1648,Chris Rowley,27,TOR,AL,0,1,0.0,40.50,2,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
1304,Sam Dyson,24,TOR,AL,0,0,0.0,40.50,2,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
6860,Juan Nicasio,33,TEX,AL,0,0,0.0,40.50,2,0,...,40-41,2-8,14-22,62-56,28-16,42-45,48-27,6-4,12-8,15-15
3377,Anthony Banda,28,NYY,AL,0,0,0.0,40.50,2,0,...,40-41,6-9,17-23,67-67,15-13,47-46,35-34,6-4,12-8,18-12
1185,Joe Beimel,27,MIN,AL,0,0,0.0,43.20,3,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
649,Aaron Brooks,24,KCR,AL,0,1,0.0,43.88,2,1,...,23-58,3-4,21-20,42-79,14-27,25-60,31-46,6-4,12-8,15-15
4220,Jacob Turner,27,DET,AL,0,1,0.0,45.00,1,1,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
6230,Jason Anderson,25,CLE,AL,0,0,0.0,45.00,1,0,...,34-47,11-9,27-31,52-51,24-35,41-45,35-41,4-6,8-12,14-16
1842,Willians Astudillo,26,MIN,AL,0,0,0.0,45.00,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
1823,Chris Gimenez,35,MIN,AL,0,0,0.0,45.00,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
2242,Adam Johnson,23,MIN,AL,0,1,0.0,47.25,2,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
922,Kyle Nelson,23,CLE,AL,0,0,0.0,54.00,1,0,...,34-47,11-9,27-31,52-51,24-35,41-45,35-41,4-6,8-12,14-16
7068,Josh Wall,27,LAA,AL,0,0,0.0,54.00,2,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
6527,Brian Tallet,33,TOR,AL,0,1,0.0,54.00,1,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
716,Jeremy Bleich,31,OAK,AL,0,0,0.0,54.00,2,0,...,24-57,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18
2729,Mike Zagurski,30,NYY,AL,0,0,0.0,54.00,1,0,...,40-41,6-9,17-23,67-67,15-13,47-46,35-34,6-4,12-8,18-12
1891,Tim Redding,27,NYY,AL,0,1,0.0,54.00,1,1,...,40-41,6-9,17-23,67-67,15-13,47-46,35-34,6-4,12-8,18-12
2543,Dave Maurer,29,TOR,AL,0,0,0.0,54.00,3,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
1486,Brian Moran,33,LAA,AL,0,0,0.0,54.00,1,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
3803,Cody Carroll,27,BAL,AL,0,0,0.0,54.00,3,0,...,52-29,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12
5979,Drew Butera,34,KCR,AL,0,0,0.0,54.00,1,0,...,23-58,3-4,21-20,42-79,14-27,25-60,31-46,6-4,12-8,15-15
5271,David McKay,25,DET,AL,0,0,0.0,54.00,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
1437,Glenn Sparkman,25,TOR,AL,0,0,0.0,63.00,2,0,...,46-35,10-9,25-20,69-58,20-15,43-50,46-23,4-6,10-10,17-13
4428,Jay Sborz,25,DET,AL,0,0,0.0,67.50,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
3458,Radhames Liz,25,BAL,AL,0,0,0.0,67.50,2,0,...,52-29,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12
2294,Carlos GÃ³mez,32,TBR,AL,0,0,0.0,81.00,1,0,...,46-35,7-5,22-25,75-52,24-11,48-44,51-19,6-4,13-7,19-11
7112,Edwar Colina,23,MIN,AL,0,0,0.0,81.00,1,0,...,40-41,12-8,19-27,66-58,21-17,37-36,50-39,7-3,12-8,18-12
655,Donnie Joseph,26,KCR,AL,0,0,0.0,81.00,1,0,...,23-58,3-4,21-20,42-79,14-27,25-60,31-46,6-4,12-8,15-15
3111,Taylor Hearn,24,TEX,AL,0,1,0.0,108.00,1,1,...,40-41,2-8,14-22,62-56,28-16,42-45,48-27,6-4,12-8,15-15
5872,JosÃ© Paniagua,29,CHW,AL,0,0,0.0,108.00,1,0,...,30-51,5-11,19-30,47-77,14-24,26-59,35-42,3-7,6-14,9-21
4209,William Cuevas,26,DET,AL,0,0,0.0,108.00,1,0,...,41-40,10-8,21-20,62-62,16-22,31-54,47-30,7-3,13-7,19-11
5787,David Carpenter,25,LAA,AL,0,0,0.0,108.00,1,0,...,35-46,7-8,22-21,57-64,16-25,35-63,38-26,4-6,8-12,10-20
3515,Jeff Ridgway,26,TBD,AL,0,0,0.0,189.00,3,0,...,46-35,7-5,22-25,75-52,24-11,48-44,51-19,6-4,13-7,19-11

In [316]:
nl_train.sort_values(by="ERA").tail(50)

,Name,Age,Tm,Lg,W_x,L_x,W-L%_x,ERA,G,GS,...,Road,ExInn,1Run,vRHP,vLHP,â‰¥.500,<.500,last10,last20,last30
5154,John Cornely,26,ATL,NL,0,0,0.0,36.00,1,0,...,52-29,8-3,23-18,81-49,23-9,55-33,49-25,7-3,11-9,17-13
3622,Phil Bickford,24,MIL,NL,0,0,0.0,36.00,1,0,...,43-38,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12
6794,Vladimir NÃºÃ±ez,34,ATL,NL,0,0,0.0,36.00,1,0,...,52-29,8-3,23-18,81-49,23-9,55-33,49-25,7-3,11-9,17-13
2040,Mauricio Llovera,24,PHI,NL,0,0,0.0,36.00,1,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
3196,Sam Tuivailala,21,STL,NL,0,0,0.0,36.00,2,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
1216,Diego Castillo,24,PIT,NL,0,0,0.0,36.00,2,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
5487,Wilmer Difo,29,PIT,NL,0,0,0.0,36.00,2,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
7457,Mike Johnston,26,PIT,NL,0,0,0.0,36.00,1,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
974,Albert Pujols,42,STL,NL,0,0,0.0,36.00,1,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
6803,Joe Paterson,26,ARI,NL,0,0,0.0,37.13,6,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
1826,Roman Quinn,25,PHI,NL,0,0,0.0,37.80,1,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
1223,Josh VanMeter,27,PIT,NL,0,0,0.0,39.00,3,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
3455,Brendon Little,25,CHC,NL,0,1,0.0,40.50,1,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
5562,Blaine Boyer,24,ATL,NL,0,0,0.0,40.50,2,0,...,52-29,8-3,23-18,81-49,23-9,55-33,49-25,7-3,11-9,17-13
543,Curtis Partch,29,PIT,NL,0,0,0.0,40.50,2,0,...,37-44,3-9,22-17,50-58,26-28,40-62,36-24,5-5,10-10,17-13
5795,Antonio Osuna,32,WSN,NL,0,0,0.0,42.43,4,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
1992,Patrick Schuster,25,PHI,NL,0,1,0.0,45.00,6,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
3453,Andrelton Simmons,32,CHC,NL,0,0,0.0,45.00,1,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
1612,Todd Zeile,38,NYM,NL,0,0,0.0,45.00,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
5204,Dave Davidson,25,FLA,NL,0,0,0.0,45.00,1,0,...,38-43,7-3,33-14,64-59,20-19,38-50,46-28,5-5,11-9,18-12
4135,Max Schrock,27,CIN,NL,0,0,0.0,45.00,1,0,...,44-37,10-5,34-29,59-55,23-25,41-47,41-33,3-7,9-11,14-16
6135,Jordan Weems,28,ARI,NL,0,1,0.0,47.25,2,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
1429,Paul Janish,26,CIN,NL,0,0,0.0,49.50,2,0,...,44-37,10-5,34-29,59-55,23-25,41-47,41-33,3-7,9-11,14-16
5719,Nate Robertson,32,PHI,NL,0,0,0.0,54.00,2,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
3851,Vin Mazzaro,29,SFG,NL,1,0,1.0,54.00,2,0,...,34-47,11-5,25-19,51-63,28-20,46-55,33-28,3-7,7-13,10-20
4651,Matt Grace,31,ARI,NL,0,1,0.0,54.00,3,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
5352,Jared FernÃ¡ndez,32,HOU,NL,0,0,0.0,54.00,2,1,...,51-30,1-8,20-21,62-51,28-21,42-43,48-29,6-4,10-10,16-14
835,John Axford,38,MIL,NL,0,0,0.0,54.00,1,0,...,43-38,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12
746,JosÃ© Reyes,35,NYM,NL,0,0,0.0,54.00,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
7737,Yunesky Maya,31,WSN,NL,0,1,0.0,54.00,1,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
2439,Sandy Rosario,24,FLA,NL,0,0,0.0,54.00,2,0,...,38-43,7-3,33-14,64-59,20-19,38-50,46-28,5-5,11-9,18-12
2577,Mike Bynum,26,SDP,NL,0,1,0.0,54.00,2,0,...,38-43,2-12,9-23,54-61,28-19,40-51,42-29,8-2,15-5,20-10
2350,Deolis Guerra,30,MIL,NL,0,0,0.0,54.00,1,0,...,43-38,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12
904,James Bourque,25,WSN,NL,0,0,0.0,54.00,1,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
1090,Dan Serafini,33,COL,NL,0,0,0.0,54.00,3,0,...,22-59,6-4,23-24,37-74,22-29,31-72,28-31,3-7,8-12,10-20
2337,Mike Zagurski,35,MIL,NL,0,1,0.0,63.00,2,0,...,43-38,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12
7335,Jason Pearson,27,STL,NL,0,0,0.0,63.00,2,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
3533,Akeel Morris,22,NYM,NL,0,0,0.0,67.50,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
4812,Trevor Bell,27,CIN,NL,0,0,0.0,67.50,2,0,...,44-37,10-5,34-29,59-55,23-25,41-47,41-33,3-7,9-11,14-16
5770,Casper Wells,28,PHI,NL,0,1,0.0,67.50,1,0,...,41-40,10-7,29-24,60-51,30-21,47-43,43-29,7-3,12-8,16-14
3428,Brailyn MÃ¡rquez,21,CHC,NL,0,0,0.0,67.50,1,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
2819,Enrique HernÃ¡ndez,26,LAD,NL,0,1,0.0,81.00,1,0,...,47-34,6-6,16-15,74-39,26-23,52-36,48-26,6-4,13-7,17-13
3366,Roel RamÃ­rez,26,STL,NL,0,0,0.0,81.00,1,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
3337,Roel RamÃ­rez,25,STL,NL,0,0,0.0,81.00,1,0,...,36-45,6-6,17-26,54-66,17-25,45-56,26-35,4-6,8-12,15-15
6758,Garrett Olson,28,NYM,NL,0,0,0.0,108.00,1,0,...,32-49,7-3,25-28,57-52,18-35,45-57,30-30,4-6,10-10,15-15
5990,Ã‰dgar GonzÃ¡lez,22,ARI,NL,0,0,0.0,108.00,1,0,...,41-40,5-4,21-21,56-57,28-21,40-50,44-28,4-6,10-10,15-15
3901,Alex Hinshaw,29,CHC,NL,0,0,0.0,135.00,2,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
1714,Chad Fox,38,CHC,NL,0,0,0.0,135.00,2,0,...,38-43,3-6,21-24,54-57,29-22,38-51,45-28,4-6,7-13,13-17
220,Jeremy Guthrie,38,WSN,NL,0,1,0.0,135.00,1,1,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20
895,Austen Williams,26,WSN,NL,0,0,0.0,162.00,2,0,...,37-44,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20

In [317]:
reg.fit(al_train[predictors], al_train["Share"])

Ridge(alpha=0.1)

In [318]:
reg.fit(nl_train[predictors], nl_train["Share"])

Ridge(alpha=0.1)

In [319]:
al_predictions = reg.predict(al_test[predictors])

In [320]:
nl_predictions = reg.predict(nl_test[predictors])

In [321]:
al_predictions = pd.DataFrame(al_predictions, columns=["predictions"], index=al_test.index)

In [322]:
nl_predictions = pd.DataFrame(nl_predictions, columns=["predictions"], index=nl_test.index)

In [323]:
al_predictions

      predictions
889      0.009806
890      0.010581
891      0.008183
892      0.017402
893      0.002720
...           ...
7102    -0.002864
7103     0.004648
7104    -0.010468
7105    -0.012188
7106    -0.011501

[435 rows x 1 columns]

In [324]:
nl_predictions

      predictions
426      0.009031
427     -0.017057
428     -0.003655
429     -0.002012
430     -0.003629
...           ...
5245     0.000052
5246    -0.009773
5247     0.000863
5248     0.124562
5249    -0.019802

[426 rows x 1 columns]

In [325]:
al_combination = pd.concat([al_test[["Name", "Share"]], al_predictions], axis=1)

In [326]:
nl_combination = pd.concat([nl_test[["Name", "Share"]], nl_predictions], axis=1)

In [327]:
al_combination.sort_values("Share", ascending=False).head(10)

                Name  Share  predictions
3413     Gerrit Cole   1.00     0.181954
5777      Sonny Gray   0.50     0.053996
2153   Kevin Gausman   0.39     0.100489
5701    Kyle Bradish   0.19     0.059014
5113   Luis Castillo   0.11     0.072779
1006      Zach Eflin   0.09     0.084525
5775     Pablo LÃ³pez   0.05     0.109205
5107    George Kirby   0.04     0.076091
6002  Framber Valdez   0.03     0.134317
2143   Chris Bassitt   0.02     0.093210

In [328]:
nl_combination.sort_values("Share", ascending=False).head(10)

                 Name  Share  predictions
3696      Blake Snell   0.97     0.087131
4300       Logan Webb   0.41     0.118926
5248       Zac Gallen   0.32     0.124562
455   Spencer Strider   0.30     0.152673
3496    Justin Steele   0.15     0.076748
2134     Zack Wheeler   0.13     0.092759
2712      Kodai Senga   0.08     0.064437
2377    Corbin Burnes   0.06     0.055302
3826         Ty Blach   0.00    -0.021259
4292     Brett Wisely   0.00     0.008079

In [329]:
from sklearn.metrics import mean_squared_error

In [330]:
mean_squared_error(al_combination["Share"], al_combination["predictions"])

0.0025632605611485633

In [331]:
mean_squared_error(nl_combination["Share"], nl_combination["predictions"])

0.002504226620429675

In [332]:
al_combination["Share"].value_counts()

Share
0.00    424
0.09      1
0.02      1
0.39      1
1.00      1
0.04      1
0.11      1
0.01      1
0.19      1
0.05      1
0.50      1
0.03      1
Name: count, dtype: int64

In [333]:
nl_combination["Share"].value_counts()

Share
0.00    418
0.30      1
0.13      1
0.06      1
0.08      1
0.15      1
0.97      1
0.41      1
0.32      1
Name: count, dtype: int64

In [334]:
#Creates a ranking for each predicted Cy Young winner, considering that's all that matters
al_combination = al_combination.sort_values("Share", ascending=False)
al_combination["Rk"] = list(range(1, al_combination.shape[0]+1))
nl_combination = nl_combination.sort_values("Share", ascending=False)
nl_combination["Rk"] = list(range(1, nl_combination.shape[0]+1))

In [335]:
al_combination.head(12)

                Name  Share  predictions  Rk
3413     Gerrit Cole   1.00     0.181954   1
5777      Sonny Gray   0.50     0.053996   2
2153   Kevin Gausman   0.39     0.100489   3
5701    Kyle Bradish   0.19     0.059014   4
5113   Luis Castillo   0.11     0.072779   5
1006      Zach Eflin   0.09     0.084525   6
5775     Pablo LÃ³pez   0.05     0.109205   7
5107    George Kirby   0.04     0.076091   8
6002  Framber Valdez   0.03     0.134317   9
2143   Chris Bassitt   0.02     0.093210  10
5691  FÃ©lix Bautista   0.01     0.054579  11
5705   Mychal Givens   0.00     0.000883  12

In [336]:
nl_combination.head(12)

                    Name  Share  predictions  Rk
3696         Blake Snell   0.97     0.087131   1
4300          Logan Webb   0.41     0.118926   2
5248          Zac Gallen   0.32     0.124562   3
455      Spencer Strider   0.30     0.152673   4
3496       Justin Steele   0.15     0.076748   5
2134        Zack Wheeler   0.13     0.092759   6
2712         Kodai Senga   0.08     0.064437   7
2377       Corbin Burnes   0.06     0.055302   8
3826            Ty Blach   0.00    -0.021259   9
4292        Brett Wisely   0.00     0.008079  10
4291    Brandon Crawford   0.00     0.015453  11
4290  Anthony DeSclafani   0.00    -0.011159  12

In [337]:
#Creates a predicted rank
al_combination = al_combination.sort_values("predictions", ascending=False)
al_combination["Predicted_Rk"] = list(range(1, al_combination.shape[0]+1))
nl_combination = nl_combination.sort_values("predictions", ascending=False)
nl_combination["Predicted_Rk"] = list(range(1, nl_combination.shape[0]+1))

In [338]:
al_combination.head(10)

                Name  Share  predictions   Rk  Predicted_Rk
3413     Gerrit Cole   1.00     0.181954    1             1
6002  Framber Valdez   0.03     0.134317    9             2
5775     Pablo LÃ³pez   0.05     0.109205    7             3
4077  Nathan Eovaldi   0.00     0.108820   97             4
2153   Kevin Gausman   0.39     0.100489    3             5
1541   Shohei Ohtani   0.00     0.094851  271             6
2143   Chris Bassitt   0.02     0.093210   10             7
5112   Logan Gilbert   0.00     0.084697   23             8
1006      Zach Eflin   0.09     0.084525    6             9
5107    George Kirby   0.04     0.076091    8            10

In [339]:
nl_combination.head(10)

                  Name  Share  predictions   Rk  Predicted_Rk
455    Spencer Strider   0.30     0.152673    4             1
5248        Zac Gallen   0.32     0.124562    3             2
4300        Logan Webb   0.41     0.118926    2             3
4942      Mitch Keller   0.00     0.093734  127             4
511    Sandy AlcÃ¡ntara   0.00     0.093718  242             5
2134      Zack Wheeler   0.13     0.092759    6             6
3696       Blake Snell   0.97     0.087131    1             7
3496     Justin Steele   0.15     0.076748    5             8
448          Max Fried   0.00     0.067420  274             9
2372  Brandon Woodruff   0.00     0.066686  264            10

In [340]:
al_combination.sort_values("Share", ascending=False).head(10)

                Name  Share  predictions  Rk  Predicted_Rk
3413     Gerrit Cole   1.00     0.181954   1             1
5777      Sonny Gray   0.50     0.053996   2            18
2153   Kevin Gausman   0.39     0.100489   3             5
5701    Kyle Bradish   0.19     0.059014   4            16
5113   Luis Castillo   0.11     0.072779   5            12
1006      Zach Eflin   0.09     0.084525   6             9
5775     Pablo LÃ³pez   0.05     0.109205   7             3
5107    George Kirby   0.04     0.076091   8            10
6002  Framber Valdez   0.03     0.134317   9             2
2143   Chris Bassitt   0.02     0.093210  10             7

In [341]:
#Gives machine points for correctly predicting the top 10 AL Cy Young vote receivers, and penalizes it for missing
def find_alcy(al_combination):
    al_actual = al_combination.sort_values("Share", ascending=False).head(10)
    al_predicted = al_combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in al_predicted.iterrows():
        if row["Name"] in al_actual["Name"].values:
            found += 1
            ps.append(found/seen)
        seen += 1
    return sum(ps) / len(ps)

In [342]:
find_alcy(al_combination)

0.7665674603174603

In [343]:
#Gives machine points for correctly predicting the top 10 AL Cy Young vote receivers, and penalizes it for missing
def find_nlcy(nl_combination):
    nl_actual = nl_combination.sort_values("Share", ascending=False).head(10)
    nl_predicted = nl_combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in nl_predicted.iterrows():
        if row["Name"] in nl_actual["Name"].values:
            found += 1
            ps.append(found/seen)
        seen += 1
    return sum(ps) / len(ps)

In [344]:
find_nlcy(nl_combination)

0.6280466737778703

In [345]:
years = list(range(2003, 2024))

In [346]:
#Shows what columns have inf values
columns_with_inf = al_train.columns[al_train.isin([np.inf, -np.inf]).any()].tolist()
print(columns_with_inf)

[]

In [347]:
#Removes infinite ERAs
al_train = al_train.replace([np.inf, -np.inf], np.nan)
al_train = al_train.dropna(subset=['ERA'])
nl_train = nl_train.replace([np.inf, -np.inf], np.nan)
nl_train = nl_train.dropna(subset=['ERA'])

In [348]:
columns_with_inf = al_train.columns[al_train.isin([np.inf, -np.inf]).any()].tolist()
print(columns_with_inf)

[]

In [349]:
al_aps = []
al_all_predictions = []

for year in years[5:]:
    al_train = al_stats[al_stats["Year"] < year]
    
    #Remove rows with infinite values in the ERA column
    al_train = al_train.replace([np.inf, -np.inf], np.nan)
    al_train = al_train.dropna(subset=['ERA'])
    
    al_test = al_stats[al_stats["Year"] == year]
    
    #Remove rows with infinite values in the ERA column from the test set
    al_test.loc[:, 'ERA'] = al_test['ERA'].replace([np.inf, -np.inf], np.nan)
    al_test = al_test.dropna(subset=['ERA'])
    
    reg.fit(al_train[predictors], al_train["Share"])
    
    al_predictions = reg.predict(al_test[predictors])
    al_predictions = pd.DataFrame(al_predictions, columns=["predictions"], index=al_test.index)
    al_combination = pd.concat([al_test[["Name", "Share"]], al_predictions], axis=1)
    al_all_predictions.append(al_combination)
    al_aps.append(find_alcy(al_combination))

In [350]:
sum(al_aps) / len(al_aps)

0.6624980772587035

In [351]:
nl_aps = []
nl_all_predictions = []

for year in years[5:]:
    nl_train = nl_stats[nl_stats["Year"] < year]
    
    #Remove rows with infinite values in the ERA column
    nl_train = nl_train.replace([np.inf, -np.inf], np.nan)
    nl_train = nl_train.dropna(subset=['ERA'])
    
    nl_test = nl_stats[nl_stats["Year"] == year]
    
    #Remove rows with infinite values in the ERA column from the test set
    nl_test.loc[:, 'ERA'] = nl_test['ERA'].replace([np.inf, -np.inf], np.nan)
    nl_test = nl_test.dropna(subset=['ERA'])
    
    reg.fit(nl_train[predictors], nl_train["Share"])
    
    nl_predictions = reg.predict(nl_test[predictors])
    nl_predictions = pd.DataFrame(nl_predictions, columns=["predictions"], index=nl_test.index)
    nl_combination = pd.concat([nl_test[["Name", "Share"]], nl_predictions], axis=1)
    nl_all_predictions.append(nl_combination)
    nl_aps.append(find_nlcy(nl_combination))

In [352]:
sum(nl_aps) / len(nl_aps)

0.6638610258483166

In [353]:
def al_add_ranks(al_combination):
    al_combination = al_combination.sort_values("Share", ascending=False)
    al_combination["Rk"] = list(range(1, al_combination.shape[0]+1))
    al_combination = al_combination.sort_values("predictions", ascending=False)
    al_combination["Predicted_Rk"] = list(range(1, al_combination.shape[0]+1))
    al_combination["Diff"] = al_combination["Rk"] - al_combination["Predicted_Rk"]
    return al_combination

In [354]:
al_ranking = al_add_ranks(al_all_predictions[1])
al_ranking[al_ranking["Rk"] < 11].sort_values("Diff", ascending=False)

                  Name  Share  predictions  Rk  Predicted_Rk  Diff
5749      Roy Halladay   0.08     0.243829   5             1     4
4414  Justin Verlander   0.10     0.195961   3             3     0
5338      Zack Greinke   0.96     0.217326   1             2    -1
6757   FÃ©lix HernÃ¡ndez   0.57     0.145019   2             5    -3
189        CC Sabathia   0.09     0.122796   4             7    -3
185       A.J. Burnett   0.00     0.027343   6            34   -28
5737  Bryan Bullington   0.00     0.015523   8            68   -60
5736       Brian Wolfe   0.00     0.003798   9           135  -126
5731        Brad Mills   0.00     0.001640   7           159  -152
5735      Brian Tallet   0.00    -0.010702  10           253  -243

In [355]:
def nl_add_ranks(nl_combination):
    nl_combination = nl_combination.sort_values("Share", ascending=False)
    nl_combination["Rk"] = list(range(1, nl_combination.shape[0]+1))
    nl_combination = nl_combination.sort_values("predictions", ascending=False)
    nl_combination["Predicted_Rk"] = list(range(1, nl_combination.shape[0]+1))
    nl_combination["Diff"] = nl_combination["Rk"] - nl_combination["Predicted_Rk"]
    return nl_combination

In [356]:
nl_ranking = nl_add_ranks(nl_all_predictions[1])
nl_ranking[nl_ranking["Rk"] < 11].sort_values("Diff", ascending=False)

                   Name  Share  predictions  Rk  Predicted_Rk  Diff
6503          Dan Haren   0.01     0.100519   5             4     1
4373       Tim Lincecum   0.63     0.204706   1             1     0
3122    Chris Carpenter   0.59     0.123527   2             2     0
3119    Adam Wainwright   0.56     0.095178   3             5    -2
6783     Javier VÃ¡zquez   0.02     0.091689   4             6    -2
1138         Aaron Cook   0.00     0.028805   6            39   -33
6514         Tom Gordon   0.00     0.009808   9            95   -86
6508  Esmerling VÃ¡squez   0.00     0.001413   7           183  -176
6513  Scott Schoeneweis   0.00    -0.012220  10           310  -300
6515     Yusmeiro Petit   0.00    -0.032301   8           351  -343

In [357]:
def al_backtest(al_stats, model, year, predictors):
    al_aps = []
    al_all_predictions = []
    for year in years[5:]:
        al_train = al_stats[al_stats["Year"] < year]
        #Remove rows with infinite values in the ERA column
        al_train = al_train.replace([np.inf, -np.inf], np.nan)
        al_train = al_train.dropna(subset=['ERA'])
        al_test = al_stats[al_stats["Year"] == year]
        #Remove rows with infinite values in the ERA column from the test set
        al_test.loc[:, 'ERA'] = al_test['ERA'].replace([np.inf, -np.inf], np.nan)
        al_test = al_test.dropna(subset=['ERA'])
        model.fit(al_train[predictors], al_train["Share"])
        al_predictions = reg.predict(al_test[predictors])
        al_predictions = pd.DataFrame(al_predictions, columns=["predictions"], index=al_test.index)
        al_combination = pd.concat([al_test[["Name", "Share"]], al_predictions], axis=1)
        al_combination = al_add_ranks(al_combination)
        al_all_predictions.append(al_combination)
        al_aps.append(find_alcy(al_combination))
    return sum(al_aps)/len(al_aps), al_aps, pd.concat(al_all_predictions)

In [358]:
al_mean_ap, al_aps, al_all_predictions = al_backtest(al_stats, reg, years[5:], predictors)

In [359]:
al_mean_ap

0.644433744744616

In [360]:
def nl_backtest(nl_stats, model, year, predictors):
    nl_aps = []
    nl_all_predictions = []
    for year in years[5:]:
        nl_train = nl_stats[nl_stats["Year"] < year]
        #Remove rows with infinite values in the ERA column
        nl_train = nl_train.replace([np.inf, -np.inf], np.nan)
        nl_train = nl_train.dropna(subset=['ERA'])
        nl_test = nl_stats[nl_stats["Year"] == year]
        #Remove rows with infinite values in the ERA column from the test set
        nl_test.loc[:, 'ERA'] = nl_test['ERA'].replace([np.inf, -np.inf], np.nan)
        nl_test = nl_test.dropna(subset=['ERA'])
        model.fit(nl_train[predictors], nl_train["Share"])
        nl_predictions = reg.predict(nl_test[predictors])
        nl_predictions = pd.DataFrame(nl_predictions, columns=["predictions"], index=nl_test.index)
        nl_combination = pd.concat([nl_test[["Name", "Share"]], nl_predictions], axis=1)
        nl_combination = nl_add_ranks(nl_combination)
        nl_all_predictions.append(nl_combination)
        nl_aps.append(find_nlcy(nl_combination))
    return sum(nl_aps)/len(nl_aps), nl_aps, pd.concat(nl_all_predictions)

In [361]:
nl_mean_ap, nl_aps, nl_all_predictions = nl_backtest(nl_stats, reg, years[5:], predictors)

In [362]:
nl_mean_ap

0.6447809234573907

In [363]:
al_all_predictions[al_all_predictions["Rk"] <= 10].sort_values("Diff").head(10)

                     Name  Share  predictions  Rk  Predicted_Rk  Diff
3954       Kevin McCarthy   0.00    -0.015340   9           348  -339
2563        Andrew Miller   0.01    -0.014683   9           299  -290
3157        Nick Tropeano   0.00    -0.009599   9           290  -281
432          A.J. Griffin   0.00    -0.009409   9           284  -275
5522     Dontrelle Willis   0.00    -0.030300   9           278  -269
4114         Yennier Cano   0.00    -0.004472  10           276  -266
5735         Brian Tallet   0.00    -0.010702  10           253  -243
4042  Francisco RodrÃ­guez   0.23    -0.002379   3           162  -159
4874            Ryan Webb   0.00     0.002403  10           166  -156
5731           Brad Mills   0.00     0.001640   7           159  -152

In [364]:
nl_all_predictions[nl_all_predictions["Rk"] <= 10].sort_values("Diff").head(10)

                   Name  Share  predictions  Rk  Predicted_Rk  Diff
3826           Ty Blach    0.0    -0.021259   9           406  -397
4510   Brusdar Graterol    0.0    -0.007366   9           376  -367
6515     Yusmeiro Petit    0.0    -0.032301   8           351  -343
5756      Josh Lindblom    0.0    -0.010410   9           316  -307
6513  Scott Schoeneweis    0.0    -0.012220  10           310  -300
3237        Mike Mayers    0.0    -0.004228  10           226  -216
3865      Mark Melancon    0.0    -0.003453  10           215  -205
4664     Brandon Morrow    0.0    -0.002811   9           203  -194
3858          Derek Law    0.0    -0.002324   9           198  -189
4161        Kris Medlen    0.0     0.002193  10           195  -185

In [365]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0       1
25  0.053797    WHIP
38  0.040233     SOS
37  0.038478   Rdiff
8   0.025105      CG
36  0.013958      RA
9   0.009536     SHO
34  0.005497  W-L%_y
1   0.002861     W_x
11  0.001112      IP
18  0.000824      SO
20  0.000450      BK
0   0.000430     Age
13  0.000323     R_x
40  0.000309    Luck
33  0.000275     L_y
24  0.000274     FIP
7   0.000130      GF
19  0.000114     HBP
23 -0.000005    ERA+
27 -0.000095     HR9
31 -0.000175    Year
10 -0.000206      SV
17 -0.000210     IBB
22 -0.000229      BF
12 -0.000237       H
4  -0.000243     ERA
32 -0.000275     W_y
14 -0.000304      ER
16 -0.000388      BB
5  -0.000409       G
30 -0.000432    SO/W
21 -0.000724      WP
29 -0.000921     SO9
6  -0.001244      GS
15 -0.001368      HR
2  -0.002482     L_x
26 -0.005627      H9
28 -0.005879     BB9
35 -0.008485     R_y
3  -0.011372  W-L%_x
39 -0.020778     SRS

In [368]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

al_mean_ap, al_aps, al_all_predictons = al_backtest(al_stats, rf, years[5:], predictors)

In [369]:
al_mean_ap

0.6213661025545474

In [370]:
nl_mean_ap, nl_aps, nl_all_predictons = nl_backtest(nl_stats, rf, years[5:], predictors)

In [371]:
nl_mean_ap

0.6509809307939319

In [372]:
al_mean_ap, al_aps, al_all_predictons = al_backtest(al_stats, reg, years[5:], predictors)

In [373]:
al_mean_ap

0.644433744744616

In [374]:
nl_mean_ap, nl_aps, nl_all_predictons = nl_backtest(nl_stats, reg, years[5:], predictors)

In [375]:
nl_mean_ap

0.6447809234573907

In [380]:
al_all_predictions[al_all_predictions["Rk"] <= 10].sort_values("Predicted_Rk")

                  Name  Share  predictions  Rk  Predicted_Rk  Diff
180       Roy Halladay   0.51     0.245333   2             1     1
5671      Corey Kluber   0.80     0.223344   1             1     0
2909  Justin Verlander   0.76     0.255761   2             1     1
6180  Justin Verlander   1.00     0.174604   1             1     0
3361       Gerrit Cole   0.59     0.193433   2             1     1
...                ...    ...          ...  ..           ...   ...
5522  Dontrelle Willis   0.00    -0.030300   9           278  -269
432       A.J. Griffin   0.00    -0.009409   9           284  -275
3157     Nick Tropeano   0.00    -0.009599   9           290  -281
2563     Andrew Miller   0.01    -0.014683   9           299  -290
3954    Kevin McCarthy   0.00    -0.015340   9           348  -339

[160 rows x 6 columns]

In [383]:
nl_all_predictions[nl_all_predictions["Rk"] <= 10].sort_values("Predicted_Rk")

                   Name  Share  predictions  Rk  Predicted_Rk  Diff
6460        CC Sabathia   0.06     0.180260   5             1     4
6771        R.A. Dickey   0.93     0.242441   1             1     0
3156    Adam Wainwright   0.41     0.231066   2             1     1
7198    Clayton Kershaw   1.00     0.306234   1             1     0
5720       Roy Halladay   1.00     0.225511   1             1     0
...                 ...    ...          ...  ..           ...   ...
6513  Scott Schoeneweis   0.00    -0.012220  10           310  -300
5756      Josh Lindblom   0.00    -0.010410   9           316  -307
6515     Yusmeiro Petit   0.00    -0.032301   8           351  -343
4510   Brusdar Graterol   0.00    -0.007366   9           376  -367
3826           Ty Blach   0.00    -0.021259   9           406  -397

[160 rows x 6 columns]

In [384]:
al_all_predictions.to_csv("al_results.csv")

In [385]:
nl_all_predictions.to_csv("nl_results.csv")