In [1]:
import requests
import os
from bs4 import BeautifulSoup
from selenium import webdriver
import time
import pandas as pd

In [2]:
years = list(range(2003, 2024)) #years that will be scraped, and used to train data

In [3]:
url_start = "https://www.baseball-reference.com/awards/awards_{}.shtml" #Cy Young award voting history

In [4]:
driver = webdriver.Edge() #user may need to add their own path, considering I run jupyter on a local host

In [5]:
#loads and saves the Cy Young webpages
for year in years:
    url = url_start.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html = driver.page_source
    with open("cyyoung/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(html)

In [6]:
#Parses html and loads AL Cy Young winners to pandas data frames for respective years
dfs = []
for year in years:
    with open("cyyoung/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, "html.parser")
    alcy_table = soup.find(id="AL_CYA_voting")
    alcy = pd.read_html(str(alcy_table))[0]
    alcy["Year"] = year
    dfs.append(alcy)

C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\197527079.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  alcy = pd.read_html(str(alcy_table))[0]

In [7]:
alcys = pd.concat(dfs) #Combines all AL Cy Young voting history to a single data frame

In [8]:
alcys

,Rank,Name,Tm,Vote Pts,1st Place,Share,WAR,W,L,W-L%,...,BB,IBB,SO,HBP,BK,WP,BF,WHIP,ERA+,Year
0,1,Roy Halladay,TOR,136.0,26.0,97%,8.1,22,7,0.759,...,32,1,204,9,1,6,1071,1.071,145,2003
1,2,Esteban Loaiza,CHW,63.0,2.0,45%,7.2,21,9,0.700,...,56,2,207,10,1,3,922,1.113,159,2003
2,3,Pedro Martinez,BOS,20.0,0.0,14%,8.0,14,4,0.778,...,47,0,206,9,0,5,749,1.039,211,2003
3,4,Tim Hudson,OAK,15.0,0.0,11%,7.4,16,7,0.696,...,61,9,162,10,0,6,967,1.075,165,2003
4,5,Jamie Moyer,SEA,12.0,0.0,9%,4.7,21,7,0.750,...,66,3,129,8,0,0,897,1.233,132,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,8,George Kirby,SEA,8.0,0.0,4%,3.9,13,10,0.565,...,19,1,172,6,0,1,757,1.038,120,2023
8,9,Framber Valdez,HOU,6.0,0.0,3%,3.2,12,11,0.522,...,57,0,200,10,0,6,808,1.126,122,2023
9,10,Chris Bassitt,TOR,4.0,0.0,2%,2.5,16,8,0.667,...,59,2,186,12,3,4,826,1.175,118,2023
10,11,Félix Bautista,BAL,3.0,0.0,1%,3.0,8,2,0.800,...,26,0,110,2,0,7,237,0.918,280,2023
11,12,Chris Martin,BOS,1.0,0.0,0%,3.2,4,1,0.800,...,8,3,46,0,0,1,199,1.032,434,2023

In [9]:
#Parses html and loads NL Cy Young winners to pandas data frames for respective years
dfs = []
for year in years:
    with open("cyyoung/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
    soup = BeautifulSoup(page, "html.parser")
    nlcy_table = soup.find(id="NL_CYA_voting")
    nlcy = pd.read_html(str(nlcy_table))[0]
    nlcy["Year"] = year
    dfs.append(nlcy)

C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\995072450.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  nlcy = pd.read_html(str(nlcy_table))[0]

In [10]:
nlcys = pd.concat(dfs) #Combines all AL Cy Young voting history to a single data frame

In [11]:
nlcys

,Rank,Name,Tm,Vote Pts,1st Place,Share,WAR,W,L,W-L%,...,BB,IBB,SO,HBP,BK,WP,BF,WHIP,ERA+,Year
0,1,Éric Gagné,LAD,146.0,28.0,91%,3.7,2,3,0.400,...,20,2,137,3,0,2,306,0.692,337,2003
1,2,Jason Schmidt,SFG,73.0,2.0,46%,6.7,17,5,0.773,...,46,1,208,5,1,7,819,0.953,180,2003
2,3,Mark Prior,CHC,60.0,2.0,38%,7.4,18,6,0.750,...,50,4,245,9,0,9,863,1.103,179,2003
3,4,Russ Ortiz,ATL,9.0,0.0,6%,2.2,21,7,0.750,...,102,7,149,4,0,5,912,1.314,113,2003
0,1,Roger Clemens,HOU,140.0,23.0,88%,5.4,18,4,0.818,...,79,5,218,6,0,5,878,1.157,145,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,4,Spencer Strider,ATL,64.0,0.0,30%,3.4,20,5,0.800,...,58,1,281,9,2,6,763,1.093,115,2023
4,5,Justin Steele,CHC,31.0,0.0,15%,3.8,16,5,0.762,...,36,0,176,7,1,9,716,1.171,146,2023
5,6,Zack Wheeler,PHI,28.0,0.0,13%,4.3,13,6,0.684,...,39,0,212,9,0,1,787,1.078,119,2023
6,7,Kodai Senga,NYM,16.0,0.0,8%,4.5,12,7,0.632,...,77,0,202,5,1,14,694,1.220,142,2023
7,8,Corbin Burnes,MIL,13.0,0.0,6%,3.5,10,8,0.556,...,66,0,200,8,1,10,784,1.069,127,2023

In [12]:
alcys.to_csv("alcys.csv") #Saves AL Cy Young canidates to CSV
nlcys.to_csv("nlcys.csv") #Saves NL Cy Young canidates to CSV

In [13]:
player_stats_url = "https://www.baseball-reference.com/leagues/majors/{}-standard-pitching.shtml"

In [14]:
#loads and saves all pitching stats webpages
for year in years:
    url = player_stats_url.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html = driver.page_source
    with open("player/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(html)

In [15]:
#Parses html and loads all pitching stats to pandas data frames for respective years
dfs = []
for year in years:
    with open("player/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
        soup = BeautifulSoup(page, "html.parser")
        soup.find("tr", class_="thead").decompose() #Removes annoying headers that appear every few rows
        soup.find("tr", class_="league_average_table italic_text").decompose()
        player_table = soup.find(id="players_standard_pitching")
        player = pd.read_html(str(player_table))[0]
        player["Year"] = year
        dfs.append(player)

C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\3798939508.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  player = pd.read_html(str(player_table))[0]

In [16]:
players = pd.concat(dfs) #Combines all pitching stats history to a single data frame

In [17]:
players

,Rk,Name,Age,Tm,Lg,W,L,W-L%,ERA,G,...,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,Year
0,1,Paul Abbott,35,KCR,AL,1,2,.333,5.29,10,...,214,93,5.63,1.531,8.9,1.5,4.9,6.0,1.23,2003
1,2,Jose Acevedo,25,CIN,NL,2,0,1.000,2.67,5,...,103,156,3.55,0.852,5.7,1.0,2.0,7.7,3.83,2003
2,3,Juan Acevedo,33,TOT,AL,1,5,.167,6.57,39,...,188,70,5.17,1.826,12.2,1.4,4.2,6.6,1.56,2003
3,4,Juan Acevedo,33,NYY,AL,0,3,.000,7.71,25,...,125,58,5.49,1.714,11.9,1.8,3.5,6.7,1.90,2003
4,5,Juan Acevedo,33,TOR,AL,1,2,.333,4.26,14,...,63,113,4.53,2.053,12.8,0.7,5.7,6.4,1.13,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1101,1060,Rob Zastryzny*,31,PIT,NL,1,0,1.000,4.79,21,...,97,94,4.32,1.790,10.5,0.4,5.7,6.5,1.15,2023
1102,1061,Seby Zavala,29,ARI,NL,0,0,NaN,0.00,1,...,2,NaN,3.26,0.000,0.0,0.0,0.0,0.0,NaN,2023
1103,1062,Angel Zerpa*,23,KCR,AL,3,3,.500,4.85,15,...,182,92,4.54,1.266,9.7,1.5,1.7,7.6,4.50,2023
1104,1063,Bruce Zimmermann*,28,BAL,AL,2,0,1.000,4.73,7,...,61,89,4.53,1.275,11.5,2.0,0.0,9.5,NaN,2023
1105,1064,Guillermo Zuñiga,24,STL,NL,0,0,NaN,4.50,2,...,8,113,-0.75,1.000,9.0,0.0,0.0,18.0,NaN,2023

In [18]:
players.to_csv("players.csv")

In [19]:
team_stats_url = "https://www.baseball-reference.com/leagues/majors/2023-standings.shtml"

In [20]:
#loads and saves all team stats webpages
for year in years:
    url = team_stats_url.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html = driver.page_source
    with open("team/{}.html".format(year), "w+", encoding="utf-8") as f:
        f.write(html)

In [21]:
#Parses html and loads all team stats to pandas data frames for respective years
dfs = []
for year in years:
    with open("team/{}.html".format(year), encoding="utf-8") as f:
        page = f.read()
    
        soup = BeautifulSoup(page, "html.parser")
        soup.find("tr", class_="thead").decompose() #Removes annoying headers that appear every few rows
        soup.find("tr", class_="league_average_table").decompose() #Removes league average row
        team_table = soup.find(id="expanded_standings_overall")
        team = pd.read_html(str(team_table))[0]
        team["Year"] = year
        dfs.append(team)

C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]
C:\Users\bianc\AppData\Local\Temp\ipykernel_21184\598876593.py:11: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  team = pd.read_html(str(team_table))[0]

In [22]:
teams = pd.concat(dfs) #Combines all team stats history to a single data frame

In [23]:
teams

,Rk,Tm,W,L,W-L%,Strk,R,RA,Rdiff,SOS,...,ExInn,1Run,vRHP,vLHP,≥.500,<.500,last10,last20,last30,Year
0,1,Atlanta Braves,104,58,0.642,L 1,5.8,4.4,1.4,-0.1,...,8-3,23-18,81-49,23-9,55-33,49-25,7-3,11-9,17-13,2003
1,2,Baltimore Orioles,101,61,0.623,L 1,5.0,4.2,0.8,0.0,...,11-6,30-16,65-44,36-17,51-39,50-22,6-4,11-9,18-12,2003
2,3,Los Angeles Dodgers,100,62,0.617,W 1,5.6,4.3,1.3,-0.1,...,6-6,16-15,74-39,26-23,52-36,48-26,6-4,13-7,17-13,2003
3,4,Tampa Bay Rays,99,63,0.611,W 2,5.3,4.1,1.2,0.0,...,7-5,22-25,75-52,24-11,48-44,51-19,6-4,13-7,19-11,2003
4,5,Milwaukee Brewers,92,70,0.568,W 1,4.5,4.0,0.5,0.0,...,10-5,29-18,70-44,22-26,51-38,41-32,6-4,13-7,18-12,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,26,Washington Nationals,71,91,0.438,W 1,4.3,5.2,-0.9,0.1,...,6-2,28-21,47-60,24-31,39-63,32-28,4-6,7-13,10-20,2023
26,27,Chicago White Sox,61,101,0.377,L 3,4.0,5.2,-1.2,0.0,...,5-11,19-30,47-77,14-24,26-59,35-42,3-7,6-14,9-21,2023
27,28,Colorado Rockies,59,103,0.364,W 1,4.5,5.9,-1.5,0.1,...,6-4,23-24,37-74,22-29,31-72,28-31,3-7,8-12,10-20,2023
28,29,Kansas City Royals,56,106,0.346,W 1,4.2,5.3,-1.1,0.0,...,3-4,21-20,42-79,14-27,25-60,31-46,6-4,12-8,15-15,2023
29,30,Oakland Athletics,50,112,0.309,L 1,3.6,5.7,-2.1,0.1,...,6-8,20-27,31-85,19-27,22-76,28-36,4-6,6-14,12-18,2023

In [24]:
teams.to_csv("teams.csv")